Repository sensasi-apps/sensasi-pos, pull requests merged in 2024-10, with the labels that each got.

#135 Menambahkan fitur untuk menambahkan data pembelian/pengadaan
  package-lock.json
  package.json
  src/app/(authenticated user)/purchases/(form)/_components/costs-input.tsx
  src/app/(authenticated user)/purchases/(form)/_components/form.tsx
  src/app/(authenticated user)/purchases/(form)/_components/items-input.tsx
  src/app/(authenticated user)/purchases/(form)/create/page-hook.ts
  src/app/(authenticated user)/purchases/(form)/create/page.tsx
  src/components/input-additional-content.tsx
Labels: hacktoberfest-accepted

#138 Melakukan pengkinian terhadap pustaka yang digunakan oleh aplikasi
  .eslintrc.json
  package-lock.json
  package.json
  src/functions/has-any-permissions.ts
Labels: INTERNAL

#141 Membuat halaman login.
  src/app/(guest)/login/page.tsx
  src/data/users.ts
Labels: AUTENTIKASI, hacktoberfest-accepted

#169 Menambahkan fitur CRUD data pengguna
  package-lock.json
  package.json
  src/app/(authenticated user)/data/users/(form)/[uuid]/hook.ts
  src/app/(authenticated user)/data/users/(form)/[uuid]/page.tsx
  src/app/(authenticated user)/data/users/(form)/_components/form.tsx
  src/app/(authenticated user)/data/users/(form)/create/hook.ts
  src/app/(authenticated user)/data/users/(form)/create/page.tsx
  src/app/(authenticated user)/data/users/hook.ts
  src/app/(authenticated user)/data/users/page.tsx
  src/enums/role.ts
  src/enums/security-question.ts
  src/functions/get-hash.ts
  src/models/db.ts
  src/models/table-types/user.ts
Labels: MANAJEMEN DATA PENGGUNA

#170 Menambahkan fitur card pada halaman Onboarding
  src/app/(guest)/onboarding/page.tsx
  src/components/onboard-card.tsx
Labels: ONBOARDING

#173 Menambahkan fitur Step pada halaman Onboarding
  src/app/(guest)/onboarding/steps/layout.tsx
  src/components/onboard-card.tsx
  src/components/stepper.tsx
Labels: ONBOARDING, hacktoberfest-accepted

#174 Memperbaiki Antarmuka Halaman Lupa Kata Sandi
  package-lock.json
  package.json
  src/app/(guest)/forgot-password/_components/email-form.tsx
  src/app/(guest)/forgot-password/_components/security-question/index.tsx
  src/app/(guest)/forgot-password/_components/security-question/question-and-answer-field.tsx
  src/app/(guest)/forgot-password/_components/security-question/security-question.tsx
  src/app/(guest)/forgot-password/_stores/security-question.ts
  src/app/(guest)/forgot-password/page.tsx
  src/stores/form-submission.ts
Labels: AUTENTIKASI, hacktoberfest-accepted

#177 Membangun Antarmuka Halaman Pengaturan Ulang Kata Sandi
  src/app/(guest)/reset-password/_components/reset-password-form/_components/confirm-password-field.tsx
  src/app/(guest)/reset-password/_components/reset-password-form/_components/confirm-pin-field.tsx
  src/app/(guest)/reset-password/_components/reset-password-form/_components/password-field.tsx
  src/app/(guest)/reset-password/_components/reset-password-form/_components/pin-field.tsx
  src/app/(guest)/reset-password/_components/reset-password-form/_stores/password-visibility.ts
  src/app/(guest)/reset-password/_components/reset-password-form/_stores/pin-visibility.ts
  src/app/(guest)/reset-password/_components/reset-password-form/index.tsx
  src/app/(guest)/reset-password/_components/reset-password-form/reset-password-form.tsx
  src/app/(guest)/reset-password/page.tsx
  src/stores/input-error-message.ts
Labels: AUTENTIKASI, hacktoberfest-accepted

#180 Menambahkan formulir dan program untuk menambahkan data gudang
  src/app/(authenticated user)/data/warehouses/(form)/create/page.tsx
  src/models/table-types/warehouse.ts
Labels: MANAJEMEN DATA GUDANG, hacktoberfest-accepted

#181 Pengkinian pustaka-pustaka dependensi
  package-lock.json
  package.json
Labels: INTERNAL

#182 Menambahkan null coalescing pada input-input
  src/app/(authenticated user)/purchases/(form)/_components/items-input.tsx
Labels: MANAJEMEN DATA PENGADAAN

#183 Pengkinian pustaka yang dibutuhkan
  package-lock.json
  package.json
Labels: INTERNAL

#184 Merincikan tipe data form dan menampilkan satuan barang
  src/app/(authenticated user)/purchases/(form)/_components/costs-input.tsx
  src/app/(authenticated user)/purchases/(form)/_components/form.tsx
  src/app/(authenticated user)/purchases/(form)/_components/items-input.tsx
  src/app/(authenticated user)/purchases/(form)/_types/form-values.ts
  src/app/(authenticated user)/purchases/(form)/create/page-hook.ts
  src/app/(authenticated user)/purchases/(form)/create/page.tsx
  src/app/(authenticated user)/purchases/page.tsx
Labels: MANAJEMEN DATA PENGADAAN

#185 Memperbaharui pustaka yang dibutuhkan
  package-lock.json
  package.json
  tsconfig.json
Labels: INTERNAL
