Repository sensasi-apps/sensasi-pos, pull requests merged in 2024-09, with the labels that each got.

#115 Membuat enum `Permission` serta templat izin aksi berdasarkan peran
  src/data/permission-templates.ts
  src/enums/permission.ts
  src/models/table-types/user.ts
Labels: INTERNAL, AUTENTIKASI, MANAJEMEN DATA PENGGUNA

#118 Menyempurnakan kerangka aplikasi
  .eslintrc.json
  package-lock.json
  package.json
  src/@types/file.ts
  src/app/(authenticated user)/dashboard/reports/page.tsx
  src/app/(authenticated user)/data/products/[id]/_hook.ts
  src/app/(authenticated user)/data/products/[id]/page.tsx
  src/app/(authenticated user)/data/products/_components/product-card/_hook.tsx
  src/app/(authenticated user)/data/products/_components/product-card/product-card.tsx
  src/app/(authenticated user)/data/products/_components/product-form/_hook.ts
  src/app/(authenticated user)/data/products/_components/product-form/product-form.tsx
  src/app/(authenticated user)/purchases/(form)/[id]/page-hook.ts
  src/app/(authenticated user)/purchases/(form)/[id]/page.tsx
  src/app/(authenticated user)/purchases/(form)/_functions/update-stocks-on-received.ts
  src/app/(authenticated user)/purchases/(form)/create/page-hook.ts
  src/app/(authenticated user)/purchases/page.tsx
  src/app/@navbar/_components/settings-dropdown-button.tsx
  src/app/_page-sections/cta.tsx
  src/app/_page-sections/hero.tsx
  src/components/barcode-scanner-camera-modal.tsx
  src/components/theme-switcher.tsx
  src/enums/page-url.ts
  src/functions/generate-ordered-uuid.ts
  src/models/db.ts
  src/models/table-types/product-movement.ts
  src/models/table-types/product-movement/additional-cost.ts
  src/models/table-types/product-movement/item.ts
  src/models/table-types/product-movement/purchase-additional-info.ts
  src/models/table-types/product-movement/sale-additional-info.ts
  src/models/table-types/product.ts
  src/models/table-types/user.ts
  src/models/table-types/warehouse.ts
Labels: INTERNAL, MANAJEMEN DATA PRODUK, MANAJEMEN DATA PENGADAAN, MANAJEMEN BASIS DATA

#120 Menambahkan cetak biru aplikasi
  CONTRIBUTING.md
Labels: DOKUMENTASI

#123 Restruktur lokasi file halaman `products` dan `purchases`
  src/app/(authenticated user)/data/products/(form)/[uuid]/_hook.ts
  src/app/(authenticated user)/data/products/(form)/[uuid]/page.tsx
  src/app/(authenticated user)/data/products/(form)/_components/page-template.tsx
  src/app/(authenticated user)/data/products/(form)/_components/product-form/hook.ts
  src/app/(authenticated user)/data/products/(form)/_components/product-form/icon-button-input-content.tsx
  src/app/(authenticated user)/data/products/(form)/_components/product-form/index.ts
  src/app/(authenticated user)/data/products/(form)/_components/product-form/product-form.tsx
  src/app/(authenticated user)/data/products/(form)/_components/product-form/props.ts
  src/app/(authenticated user)/data/products/(form)/create/_hook.ts
  src/app/(authenticated user)/data/products/(form)/create/page.tsx
  src/app/(authenticated user)/data/products/[id]/_hook.ts
  src/app/(authenticated user)/purchases/(form)/[uuid]/page-hook.ts
  src/app/(authenticated user)/purchases/(form)/[uuid]/page.tsx
  src/app/@navbar/_components/settings-dropdown-button.tsx
  src/app/@navbar/default.tsx
  src/app/_page-sections/hero.tsx
  src/app/layout.tsx
  src/enums/page-url.ts
  src/functions/has-any-permissions.ts
  src/functions/has-logged-in-user.ts
  src/functions/is-uuid-string.ts
  src/models/table-types/user.ts
Labels: LANDING, INTERNAL, AUTENTIKASI

#122 merubah komponents input menjadi select pada satuan jual
  src/app/(authenticated user)/data/products/(form)/_components/product-form/product-form.tsx
Labels: MANAJEMEN DATA PRODUK

#126 merubah dari button menjadi drag n drop & button
  src/components/image-input/image-input.tsx
Labels: MANAJEMEN DATA PRODUK

#133 Membuat file CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: DOKUMENTASI
